#pragma once
#include <Windows.h>

const int Size = 11;

enum Ship
{
	Torpedo_Boats = 3, Destroyers = 2, Cruisers = 1, Battleship= 0
};

enum Way
{
	Left = 1, Right = 2, Up = 3, Doun = 4
};

enum ConsoleColors
{


	BLACK = 0,

	DARKBLUE = FOREGROUND_BLUE,

	DARKGREEN = FOREGROUND_GREEN,

	DARKCYAN = FOREGROUND_GREEN | FOREGROUND_BLUE,

	DARKRED = FOREGROUND_RED,

	DARKMAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,

	DARKYELLOW = FOREGROUND_RED | FOREGROUND_GREEN,

	DARKGRAY = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,

	GRAY = FOREGROUND_INTENSITY,

	BLUE = FOREGROUND_INTENSITY | FOREGROUND_BLUE,

	GREEN = FOREGROUND_INTENSITY | FOREGROUND_GREEN,

	CYAN = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,

	RED = FOREGROUND_INTENSITY | FOREGROUND_RED,

	MAGENTA = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,

	YELLOW = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,

	WHITE = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,

};

void SetForegroundColor(ConsoleColors color);
